### PR TITLE
initialize jekyll

### PR DESCRIPTION
**Pull request by rakutenjeff**
Initialized jekyll by "jekyll new ."
Modified _config.yml similar as https://github.com/w3c/epub-wg/
Created an empty _layouts/home.html will feed more information there.

Next step: brush up home.html and add a place for each TF

### CODE REVIEW

**Review by iherman — CHANGES_REQUESTED** [review]
I cannot really judge things based only on the sources. I presume you know that you can run jekyll locally, ie, you can test the website on your own machine; I trust you on that.

One specific, but potentially more complex issue is the following. You have set the base URL in the `_config.yml` file to `/community/publishingcg`. I.e., your expectation is that this website would appear at

```
https://www.w3.org/community/publishingcg
```

in other words, that this would "replace" the current, official CG home page. I do not know what the current policy is, but I know that when I wanted to do the same thing for the BG, I did not get the authorization to do so. Hence the duality, for the BG, of having

```
https://www.w3.org/community/publishingbg/
https://w3c.github.io/publ-bg/
```

(The BG membership does not really use the site, so it did not turn out to be a problem.)

As I said, I do not know what the current policy is at W3C; I have to defer to @swickr on this. What I think _should_ be possible is to set up a redirection from

```
https://www.w3.org/publishing/groups/publishingcg/
```

to this website, in which case the "base" value in the configuration should be set to:

```
/publishing/groups/publishingcg/
```

Again, I have to defer to @swickr on this.

Cc @swickr

**Comment by Jeffxz** [comment]
Thanks @iherman. Yes I did run it locally to test.
It's a good point. I also had question of where should it be hosted. Right now we have these which seems a bit duplicated.

https://www.w3.org/community/publishingcg/
https://w3c.github.io/publishingcg/ (the readme in this repo)

Ideally if possible I would like to have template of https://www.w3.org/community/publishingcg/, customize it and put to here with jekyll (https://www.w3.org/publishing/groups/publishingcg/). And then https://www.w3.org/community/publishingcg/ can redirect to https://www.w3.org/publishing/groups/publishingcg/. I can also understand that might take a bit time but also wanted to check if this is doable with @swickr.

Meanwhile I don't mind this jekyll to stay in https://w3c.github.io/publishingcg/ for a bit longer. All we needed is to provide a convenient place (with nav and aside) to let ppl easily find where they should go (including each TFs entry point) from CG home page. This is a bit difficult to be done by just markdown. I do like the theme of https://www.w3.org/community/publishingcg/ but I have no idea how to customize it.

**Comment by iherman** [comment]
@rakutenjeff,

For the time being, I would say install the whole jekyll environment in this (i.e., `https://w3c.github.io/publishingcg/ `) repo and let us get it running as a bona fide site on github.io. We can then test it.

There is already a pointer from  

```
https://www.w3.org/community/publishingcg/ 
```

to this repo (on the right-hand side), so if we say that this is the repo for real work, I think people will find it. 

If we do a redirection from:

```
https://www.w3.org/publishing/groups/publishingcg/
```

(which is doable, and easy to do) then we can probably add that reference to the official home page, too. What seems to be problematic is _any_ redirection from 

```
https://www.w3.org/community/publishingcg/ 
```

---

You seem to have two github accounts:  @rakutenjeff and @Jeffxz...

**Comment by rakutenjeff** [comment]
Thanks @iherman just keep using github.io sounds good to me.
Yeah, one is for work and one is for private. Sometimes I just mixed them...

**Pull request merged**
